### ISSUE TITLE
Improve page footer 

### ISSUE THREAD

**Issue by denisakp** [blablageeks/open-shop#5]
### Is your feature request related to a problem? Please describe

The current footer of our store feels incomplete and minimally functional, which might affect user engagement and accessibility.

### Describe the solution you'd like

I propose a redesign of the footer to make it more informative and user-friendly. 

**Use Case and Benefits**

- Use Case: Customers often scroll to the footer to find contact information, or follow social media links.
- Benefits:  A visually appealing footer contributes to the overall aesthetic of the site, making the user experience more pleasant

**Potential Challenges**

The challenge will involve designing a footer that is not only functional but also fits well with the existing website layout without being too intrusive or slowing down the page load times. Responsive design considerations must be made to ensure the footer looks good on all devices.

**Suggested Implementation**

The new footer could be designed using a flexible grid layout to accommodate different elements effectively. As example, here is an idea of a possible footer:

![footer](https://github.com/blablageeks/open-shop/assets/31835100/88bf98a4-229a-4433-b55d-30867e9999f9)

### Impact on Existing Features

the redesign should not negatively impact existing features but must be tested extensively to ensure it integrates seamlessly with the rest of the site sections.

### Describe alternatives you've considered

Alternatively, keeping the footer simple with only essential community name and the mention notice could be considered, but this might not fully tap into the potential of using the footer as a strategic space for user engagement and navigation aid.

**Additional context**
N/A

**Comment by agusaar** [comment]
I would like to work on it!

**Comment by denisakp** [comment]
> I would like to work on it!

for sure @agusaar.  Go on
